name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Build with Maven
        run: xvfb-run mvn verify --file pom.xml
        
      - name: Run tests with Xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" mvn test

      - name: Run integration tests with Xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" mvn verify -Pintegration-tests
        
      - name: Test with JaCoCo
        run: xvfb-run mvn test jacoco:report

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: xvfb-run mvn coveralls:report

            
